{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-backup-gcs.fullname" . }}
  labels:
    {{- include "mongodb-backup-gcs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.gcsKeyContent }}
  gcs-key.json: {{ .Values.gcsKeyContent }}
  {{- else }}
  gcs-key.json: {{ .Values.gcsKeyContent | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.password }}
  mongodb-password: {{ .Values.mongodb.password | b64enc | quote }}
  {{- end }}
{{- end }}
